### PR TITLE
more progress building ncl

### PR DESCRIPTION
**Pull request by edhartnett**

### CODE REVIEW

**Comment by rbrownrigg** [comment]
Ed,

This latest build is very close. There are a large number of link errors,
but most of them attributable to just a couple of things:

- The HDF5 and the EOS libraries need to be added
- I don't see where the lex/yacc processes are getting invoked?  This may
be the source of a large number of undefined references to symbols like
"cur_line_number', 'the_input_buffer', etc.

HTH...
Rick

**Comment by edhartnett** [comment]
Tell me what lex/yacc operations should occur...

**Comment by rbrownrigg** [comment]
There are the following targets in the existing makefile. Oddly, and
reasons I've never known, the traditional output products fromlex/yacc
merely get renamed, and those are what show up in the link command for
NCL.  BTW: I've also attached what the link line currently looks like as
well.

In the Makefile, the $(LEX) macro is simply defined as "flex".  The $(YACC)
macro is initially defined as "yacc". but then gets redefined in the terms
of the macro $(NYACC), which points to a binary build under
..../ncl/ni/src/nyacc.  So NCL is carrying around its own yacc. I tried
substituing "bison" once, and I can't remember all the details, but it did
not work.

Makefile targets:
------------------------
scanapi.c: scanner.c
        $(CP) scanner.c scanapi.c

# scanapi.o: scanapi.c
#       $(CC) -c $(API_DEFS) $(CFLAGS) $<

parseapi.c: parser.c
        $(CP) parser.c parseapi.c

# parseapi.o: parseapi.c
#       $(CC) -c $(API_DEFS) $(CFLAGS) $<

scanner.c:      lex.yy.c
        $(CP) lex.yy.c scanner.c

parser.h:       y.tab.h
        $(CP) y.tab.h parser.h
        $(CP) $@ ncarg/ncl

parser.c:       y.tab.c
        $(CP) y.tab.c parser.c

lex.yy.c: ncl.l
        $(LEX) ncl.l

y.tab.c y.tab.h: ncl.y
        $(YACC) -d -t ncl.y

Link line:
--------------
g\+\+ -ansi -fPIC -fopenmp -std=c99
-Wl,-rpath=/scratch/local/packages/gcc/lib64 -D_FILE_OFFSET_BITS=64
-D_LARGEFILE_SOURCE -pg -g -O3  -rdynamic   -o ncl Ncl.o io.o NclHLUObj.o
NclApi.o guiFuncs.o NclDriver.o             scanner.o parser.o MathFuncs.o
NclTypedouble.o NclTypefloat.o             NclTypeint.o NclTypelogical.o
            NclTypelong.o NclTypeobj.o             NclTypeshort.o
NclTypestring.o             NclTypeint64.o NclTypeuint64.o
NclTypeubyte.o             NclTypeushort.o NclTypeuint.o NclTypeulong.o
        NclTypebyte.o NclTypechar.o TypeSupport.o
NclMultiDValData.o AddFileFormats.o AttSupport.o DataSupport.o
FileSupport.o Formats.o GetGrids.o             AdvancedFileSupport.o
        NclAdvancedFile.o NclAdvancedGroup.o             InitData.o
Memory.o NclAtt.o NclCCM.o             NclCoordVar.o NclData.o NclGroup.o
NclFile.o NclFileVar.o             NclGRIB.o NclMultiDValnclfileData.o
        NclNetCdf.o NclOneDValCoordData.o NclType.o
NclTypelist.o NclVar.o VarSupport.o             ctoiee.o date.o qu2reg3.o
rowina3.o scm0.o ncepcode.o              NclHDF.o              NclNewHDF5.o
NclHDF5.o h5reader.o h5writer.o                          NclNetCDF4.o
        NclGRIB2.o NclOGR.o NclAdvancedOGR.o AddBuiltIns.o AddHLUObjs.o
        AddIntrinsics.o Execute.o             Machine.o OpsFuncs.o
SrcTree.o             Symbol.o Translate.o              NclHLUVar.o
HLUSupport.o             NclMultiDValHLUObjData.o
BuiltInSupport.o BuiltInFuncs.o             javaAddProto.o javaAddFuncs.o
            userAddProto.o userAddFuncs.o             HLUFunctions.o
yywrap.o craybin.o             complete.o editline.o sysunix.o
ListSupport.o             NclList.o NclMultiDVallistData.o
NclProf.o NclTime.o PrintToken.o             subprocess.o fortranio.o
-L../../.././ni/src/lib/nfp -lnfp -L../../.././ni/src/lib/nfpfort -lnfpfort
-L../../.././ni/src/lib/hlu -lhlu -L../../.././ncarg2d/src/libncarg -lncarg
-L../../.././ncarg2d/src/libncarg_gks -lncarg_gks
-L../../.././common/src/libncarg_c -lncarg_c -L../../.././ngmath/src/lib
-lngmath -L/scratch/nclbuild/lib -L/scratch/local/lib -L/usr/local/lib
-L/usr/lib64 -L/usr/lib -lnetcdf -lcurl  -lhdf5_hl -lhdf5 -lsz  -lmfhdf
-ldf -ljpeg -lz -lsz -lhdf5_hl -lhdf5 -lsz -lz -lgdal -lproj -ljpeg
-ludunits2 -lexpat  -lgrib2c -ljasper -lpng -lz -ljpeg -lpng -lz -lcairo
-lXrender -lfontconfig -lpixman-1 -lfreetype -lexpat -lpng -lz -lbz2
-L../../.././external/sphere3.1_dp -lsphere3.1_dp
-L../../.././external/fftpack5_dp -lfftpack5_dp
-L../../.././external/lapack -llapack_ncl -L../../.././external/blas
-lblas_ncl -lX11 -lXext -lgfortran -lm -lm  -ldl

**Comment by edhartnett** [comment]
OK, let me take a look at implementing those.

**Comment by edhartnett** [comment]
OK, I actually had those targets but was not adding parseapi.c and scanapi.c to the source code list. I have added it and it seems to find many more functions now.

**Pull request merged**
