### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by zklaus**

### CODE REVIEW

**Comment by erogluorhan** [comment]
Thanks a lot for putting this together! Please see my comments below:

- CI still seems to be failing at the same "ncl command not found" error under the "Run tests" as it does in PR #170 . I couldn't figure that out yet in that PR; please let me know if you have any thoughts on it.
   - This is also what happened even with the CircleCI builds,  a few times in the past , last one about 9 months ago on the develop branch: https://app.circleci.com/pipelines/github/NCAR/ncl/128/workflows/23305cdd-0a36-420f-b984-8c4cc390168b/jobs/132 
- I agree with your modification to the ci.yml to clean it up. Just an FYI: My main motivation with the version in PR #170 (even though it would need cleanup, too) was to get the CI run as well make the workflow file look as close as possible to the rest of the GeoCAT toolkits' workflows. This is not a necessity but I aimed at getting the workflow easily manageable by the whole team. Though, I am fine with this new cleaned-up version here.

**Comment by zklaus** [comment]
Thanks, @erogluorhan. You are completely right that this does not solve build issues. It only addresses the ci itself, i.e. with this in place, the build issues can be addressed in other PRs and tracked properly. But if you prefer to try to address those here as well, that's completely fine with me. It just means that we cannot easily try out different approaches to the build problems in parallel and that we create a longer standing PR which always increases the risk of further conflicts.

I didn't know about your other motives regarding consistency across the GeoCAT workflows and that does make sense, so feel free to pick and choose the things that you like. I do think that it makes sense to drop the Python requirement because Python really doesn't play into this at all.

**Comment by erogluorhan** [comment]
> Thanks, @erogluorhan. You are completely right that this does not solve build issues. It only addresses the ci itself, i.e. with this in place, the build issues can be addressed in other PRs and tracked properly. But if you prefer to try to address those here as well, that's completely fine with me. It just means that we cannot easily try out different approaches to the build problems in parallel and that we create a longer standing PR which always increases the risk of further conflicts.

> I didn't know about your other motives regarding consistency across the GeoCAT workflows and that does make sense, so feel free to pick and choose the things that you like. I do think that it makes sense to drop the Python requirement because Python really doesn't play into this at all.

All sounds good to me, @zklaus , thanks! Let me get it merged to my PR then let us get that merged to develop, too. After that, we could keep trying to fix the actual builds. I am open to any suggestions, help, etc as my NCL knowledge is limited.

**Comment by erogluorhan** [comment]
> 

@zklaus, just an FYI: I later decided to avoid the code duplications for a number of steps (e.g. "cancel previous runs", "Build NCL", "Run tests", etc.) that would come from both  "Build and test on Linux" and "Build and test on OSx" jobs. Therefore, instead of getting this merged directly, I have incorporated the significant improvements from here to my PR.

**Comment by zklaus** [comment]
That's perfectly fine. Thanks for sticking with it.

**Pull request closed without merging**
