### PR TITLE
Added Github Actions workflow for CI tests

### PR DESCRIPTION
**Pull request by erogluorhan**
This PR was originally aimed at replacing the CircleCI configuration with a Github Actions workflow. However, to get the things up and running with this new configuration, a number of things had to be done on the way:

- `triangle.h` and `triangle.c` have been added into `/ni/src/lin/hlu`
- `mamba_build.sh` has been added because `conda` builds had a lot of conflicts that couldn't be resolved in Github Actions
- Two different Github Actions workflows, `ci_mamba.yml` and `ci_conda.yml_conflicts` \, have been created. They are very similar to each other (in fact the same functionality), but one uses micromamba and the other uses codna as the names suggest. The conda one is extensioned ".yml_conflicts" just to avoid it being used by Github Actions for now as it fails due to conda build conflicts.

### CODE REVIEW

**Comment by zklaus** [comment]
We'll need to install a couple of dependencies from outside conda. I created #182, which targets this branch (`github_actions`), not `develop`, to add this. Feel free to either merge that branch into this one or to manually integrate the changes. I suspect that we'll have to add tcsh to the macos one as well, but let's see how far installation of xquartz gets us.

**Comment by erogluorhan** [comment]
> We'll need to install a couple of dependencies from outside conda. I created #182, which targets this branch (`github_actions`), not `develop`, to add this. Feel free to either merge that branch into this one or to manually integrate the changes. I suspect that we'll have to add tcsh to the macos one as well, but let's see how far installation of xquartz gets us.

Thanks a lot for this! I was looking into fixing things through bash but it took much of my time yesterday. I've merged your PR into here, so let's see

**Comment by zklaus** [comment]
Nice, @erogluorhan!

I think we are almost there. I would suggest to remove the circleci completely (unless you intend to fix it for some particular reason). I think we are also not using Python at all in the build process, right? In that case, we can remove the whole Python matrix thing and just build it all once. Seeing how almost every step in the workflow separates between linux and osx with an `if`, I also think that it might make sense to do those two in separate jobs instead, using concrete `runs-on:`'s instead of the matrix feature there as well.

Then we can move some of the patches over from the conda-forge feedstock to make the output more manageable and address the final outstanding build problems.

**Comment by erogluorhan** [comment]
Yes @zklaus I agree with all of what you mentioned and they are in my agenda, thanks! I spent my time and dirty coding on getting the Github Action workflow but couldn't succeed yet. Feel free to step in if you have any ideas; otherwise, I am getting a second look from a colleague. I hope we can get this up and running soon.

**Comment by zklaus** [comment]
Thanks, @erogluorhan, I think #183 addresses all aspects of the build process discussed above. Now it is about fixing the build itself. This will likely include porting some patches from conda-forge. Maybe we should merge #183 here before, and possibly even this PR, even though the CI still fails? I think with that, the CI does what it should and we can focus on fixing the source code itself.

The last open question on CI technicalities is how to proceed with circle ci. I have removed the configuration file in #183, but of course circleci doesn't like that very much. I think the options are basically to deactivate the project in the circleci or to fix the circleci build (which we might be able to do now that we have a better handle on things in the GH actions).

**Comment by erogluorhan** [comment]
Hi @zklaus , I have made some progress finally! If you have time and can look at it, please let me know what you think. I think we can go with its current shape as we got the ubuntu CI tests up and running.

cc: @anissa111

**Review by anissa111 — APPROVED** [review]

**Pull request merged**
